EXPENSE_OPTIONS = (
    ('food', 'Food'),
    ('housing', 'Housing'),
    ('transportation', 'Transportation'),
    ('entertainment', 'Entertainment'),
    ('education', 'Education'),
    ('healthcare', 'Healthcare'),
    ('utilities', 'Utilities'),
    ('clothing', 'Clothing'),
    ('phone', 'Phone'),
    ('personal_care', 'Personal Care'),
    ('pet_care', 'Pet Care'),
    ('child_care', 'Child Care'),
    ('memberships_and_subscriptions', 'Memberships and Subscriptions'),
    ('gifts', 'Gifts'),
    ('travel', 'Travel'),
    ('debt_repayment', 'Debt Repayment'),
    ('savings', 'Savings'),
    ('investments', 'Investments'),
    ('emergency_fund', 'Emergency Fund'),
    ('large_purchases', 'Large Purchases'),
    ('legal', 'Legal'),
    ('taxes', 'Taxes'),
    ('other', 'Other'),
)
